// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlhL0hRv714BOXs_6Y9B5FV8FmT7wXKQI',
    appId: '1:919051261674:web:d0e431f0fe0777927a2993',
    messagingSenderId: '919051261674',
    projectId: 'itsme-65d61',
    authDomain: 'itsme-65d61.firebaseapp.com',
    storageBucket: 'itsme-65d61.appspot.com',
    measurementId: 'G-LKYVZM1CRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBas3xgO1l8wxzZsETKbk8IhQcIFjx_BmA',
    appId: '1:919051261674:android:ee26a8c62981478d7a2993',
    messagingSenderId: '919051261674',
    projectId: 'itsme-65d61',
    storageBucket: 'itsme-65d61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBynFolOav5OnyoMC8SGMlC1rDLqYHzsIw',
    appId: '1:919051261674:ios:536922c127ed25877a2993',
    messagingSenderId: '919051261674',
    projectId: 'itsme-65d61',
    storageBucket: 'itsme-65d61.appspot.com',
    iosBundleId: 'com.example.flutterwebtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBynFolOav5OnyoMC8SGMlC1rDLqYHzsIw',
    appId: '1:919051261674:ios:6071362666d34a577a2993',
    messagingSenderId: '919051261674',
    projectId: 'itsme-65d61',
    storageBucket: 'itsme-65d61.appspot.com',
    iosBundleId: 'com.example.flutterwebtest.RunnerTests',
  );
}
